#! /bin/bash

# A utility making use of all the scripts relating to videos and download
# automation.

source ~/.bashrc
# set as an environment variable
queue=$QUEUE

function usage {
    echo "Usage for dv:"
    echo "      dv -h                   Brings up this help screen"
    echo "      dv -q                   Downloads the queue from Youtube (default)"
    echo "      dv -p [url] [name]      Downloads the playlist with name"
    echo "      dv -lp [url] [name]     Downloads a large playlist with name"
    echo "      dv -u [user] [pass] [video_file]      Uploads the video file to Facebook"
    echo "      dv -m [magnet_file]     Saves the magnet urls into torrent files and launches rtorrent"
}

function queue {
    cd ~/Desktop
    ~/Documents/personal_projects/bookmarklets/vid/vid.sh $queue queue
}

choice=0

if [[ $# > 4 || ($# == 1 && $1 == "-h") ]]; then
    usage
elif [[ $# == 0 || ($# == 1 && $1 == "-q") ]]; then
    queue
elif [[ $# == 3 && $1 == "-p" ]]; then
    cd ~/Desktop
    ~/Documents/personal_projects/bookmarklets/vid/vid.sh $2 $3
elif [[ $# == 3 && $1 == "-lp" ]]; then
    cd ~/Desktop
    python3 ~/Documents/personal_projects/bookmarklets/vid/parallel_pl.py $2 $3
elif [[ $# == 4 && $1 == "-u" ]]; then
    python3 ~/Documents/personal_projects/bookmarklets/vid/upload_vid.py $2 $3 $4
elif [[ $# == 2 && $1 == "-m" ]]; then
    ~/Documents/personal_projects/bookmarklets/vid/magnet.sh $2
else
    usage
fi
